### PR TITLE
Create mystiq_sv.ts

### PR DESCRIPTION
**Pull request by eson57**
@llamaret Here's Swedish translation if you want.

### CODE REVIEW

**Comment by llamaret** [comment]
Checking
Thanks

**Comment by llamaret** [comment]
> @llamaret Here's Swedish translation if you want.

Why did you close the PR???

**Comment by llamaret** [comment]
Adding swedish translation. Thanks Brother

**Comment by eson57** [comment]
> > @llamaret Here's Swedish translation if you want.
> 
> Why did you close the PR???

Git said it was rejected. Very confusing for me, not being an expert.

**Comment by llamaret** [comment]
Ufff, sorry @eson57 , I deleted your last comment , was an accident
BTW, the swedish language pack is added. welcome to mystiq project

**Comment by llamaret** [comment]
@eson57 

photo_2019-12-30_08-17-07

**Comment by eson57** [comment]
Looks great, except for the buttons. ;)

**Comment by llamaret** [comment]
> Looks great, except for the buttons. ;)

The lower buttons appear in the base language of the system. My system is in Spanish, so it comes out in Spanish. In your system it would come out in Swedish, without problems

**Pull request closed without merging**
